- pom.xml
I was suddenly having issues with the maven shade plugin, and this seems to fix it
> Update some maven plugins

- pom.xml
> Shade in Snakeyaml so that we always use the same version, and don't run into weird issues with spigot 1.16

- VoxelSniperCore/src/main/java/com/github/kevindagame/util/BlockHelper.java
> Fix the raytracing not working above or below world height

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/BlockResetSurfaceBrush.java
This closes #96, originally mentioned in [#82 (comment)](https://github.com/KevinDaGame/VoxelSniper-Reimagined/pull/82#discussion_r1057909600)
> Improved BlockResetSurface logic

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/perform/PerformerBrush.java
> fix Some performer brushes repeat old operations

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/perform/PerformerBrush.java
- buildSrc/src/main/kotlin/voxel-core.gradle.kts
Fixed PerformerBrush locations not clearing
> Version 8.4.2

- VoxelSniperCore/src/main/java/com/github/kevindagame/command/VoxelBrushCommand.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/snipe/SnipeTool.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/snipe/Sniper.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushChangedEvent.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/events/player/PlayerBrushSizeChangedEvent.java
> #112: Fixed NPE when joining server without voxelsniper permissions

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/PolyBrush.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/property/BiomeProperty.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/property/PerformerProperty.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/property/PolyProperty.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/util/Messages.java
- VoxelSniperCore/src/main/resources/lang.yml
@Lennart99 What colour should they be? 
Don't like how they look now
> Update polybrush info to show properties

- VoxelSniperCore/build.gradle.kts
- VoxelSniperCore/src/main/java/com/github/kevindagame/util/Messages.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/util/VersionChecker.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/fileHandler/VoxelSniperConfiguration.java
- VoxelSniperCore/src/main/resources/config.yml
- VoxelSniperCore/src/main/resources/lang.yml
- VoxelSniperCore/src/test/java/com/github/kevindagame/util/VersionCheckerTest.kt
- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/SpigotVoxelSniper.java
- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/VoxelSniperListener.java
- buildSrc/src/main/kotlin/voxel-core.gradle.kts
An OP will get a message on join if there is a new update
> Add update checker

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/PolyBrush.kt
> fix message formatting in PolyBrush

- README.md
> Add java version to README.md

- VoxelSniperSpigot/build.gradle.kts
- buildSrc/src/main/kotlin/voxel-core.gradle.kts
- Bumped versions for adventure-api and snakeyaml
- Changed testImplementation of spigot to 1.17
- Changed runServer version to 1.19.4
> Bump versions

- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/SpigotVoxelSniper.java
What does your pull request do?
images._
> Add support for arclight materials

- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/Version.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/biome/VoxelBiome.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/entity/entitytype/VoxelEntityType.java
- VoxelSniperSpigot/build.gradle.kts
- gradle.properties
Add support for minecraft 1.20
> Implement Minecraft 1.20 (spigot)

- VoxelSniperCore/src/main/java/com/github/kevindagame/util/BlockIterator.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/block/BlockFace.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/world/IWorld.java
- VoxelSniperForge/build.gradle
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/world/ForgeWorld.java
- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/world/SpigotWorld.java
- gradle.properties
Implement BlockIterator
Tested with linebrush
> Implement our own BlockIterator based on bukkit's

- VoxelSniperSpigot/build.gradle.kts
> group run paper

- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/block/ForgeBlock.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/mixin/MixinBlockStateBase.java
- VoxelSniperForge/src/main/resources/voxelsniperforge.mixin.json
- settings.gradle.kts
What does your pull request do?
no-physics now works on forge
run the following commands:
/b ball
/b ball P mp
/v snow
snow won't disappear (although it does seem to break after while, might be related to randomtickspeed)
images._
please forgive me for this not being a gif :P
> implemented no-physics setBlockData for forge

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/AbstractBrush.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/PolyBrush.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/operation/BlendOperation.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/operation/PolyOperation.kt
- VoxelSniperCore/src/test/java/com/github/kevindagame/brush/polymorphic/PolymorphicBrushTest.kt
Restore the original functionality of the blendball brush. I know this is a hacky fix, but for now it should be fine
> Restore blendball to original functionality

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/SignOverwriteBrush.java
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/property/PerformerProperty.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/polymorphic/property/PolyProperty.kt
- VoxelSniperCore/src/main/java/com/github/kevindagame/util/Utils.kt
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/blockstate/ExtendedBlockState.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/blockstate/sign/ForgeSign.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/entity/Painting/ForgePainting.java
- Implements Signs for Forge, fixes SignOverwriteBrush for Forge
- Added tab-completion to SignOverwriteBrush
images._
Use the brush on Forge ;)
> Implemented ForgeSign, added tab-completion to SignOverwriteBrush

- VoxelSniperCore/src/main/java/com/github/kevindagame/voxelsniper/blockdata/leaves/ILeaves.kt
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/ForgeVoxelSniperListener.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/VoxelSniperForge.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/blockdata/ForgeBlockData.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/blockdata/leaves/ForgeLeaves.kt
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/blockdata/waterlogged/ForgeWaterlogged.kt
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/entity/ForgeEntity.java
- VoxelSniperForge/src/main/java/com/github/kevindagame/voxelsniperforge/world/ForgeWorld.java
What does your pull request do?
#198 
- Implement ForgeBlockData::getCopy
- Implement Leaves
- Implement Waterlogged
- Implement ForgeWorld::regenerateChunk
- Cache world instead of creating new one (same as we do in spigot implementaion)
images._
> Implemented final Forge features

- VoxelSniperForge/build.gradle
- gradle.properties
> Bump forge to 1.20.1

- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/SpigotVoxelSniper.java
- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/integration/bstats/ServerSizeCategoryCounter.kt
- VoxelSniperSpigot/src/test/java/com/github/kevindagame/voxelsniper/integration/bstats/ServerSizeCategoryCounterTest.kt
Add the bstats online players drilldown pie chart
Start a server and get n players online
> Implement advanced online players chart

- VoxelSniperSpigot/src/main/java/com/github/kevindagame/voxelsniper/SpigotVoxelSniper.java
Resolve memory leak when unloading worlds
> Remove cached worlds on unload

- VoxelSniperForge/build.gradle
- gradle.properties
> Update Forge to 1.20.2

- README.md
What does your pull request do?
images._
> Updated forge versions in README.md

- README.md
Update readme to include fabric
> Update readme to include fabric

- VoxelSniperCore/src/main/java/com/github/kevindagame/util/schematic/SchematicReader.kt
- buildSrc/src/main/kotlin/voxel-core.gradle.kts
- settings.gradle.kts
Update Schematic4j dependency for stencils
close #230
> Update schematic4j, fixing a breaking bug with large schematics

- VoxelSniperCore/src/main/java/com/github/kevindagame/brush/FillDownBrush.java
> fix FillDownBrush below y=0
